---
  # - hosts: web
  #   become: true
  #   gather_facts: false
  #   roles:
  #   - web

  # - hosts: mysql
  #   become: true
  #   gather_facts: false
  #   roles:
  #   - mysql

  - hosts: containers-inventory
    become: true
    gather_facts: false
    roles:
    - test_custom


