name: Testing

on:

  repository_dispatch:
    types:
      - "build"

  schedule:
    - cron: "0 0 1 1 *"
    
  push:
    branches:
      - "main"
      - "feature/**"
      - "!feature/ABCD"
    tags:
      - "*"
      - "!Not This"
    paths:
      - "*"
      - "!Not this"

  pull_request:
    branches:
      - "main"
    types:
      - "opened"


jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:

    - name: Check post variable
      run: echo ${{ github.event.client_payload.name }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Listing
      run: ls -lhtr
    - name: Print Something
      run:  cat /etc/*rel* 
  
  second-job:
    needs: [first-job]
    runs-on: ubuntu-latest
    steps:
    - name: Print Something 2
      run:  uname -a
  