name: Testing

on: [push]

jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Listing
      run: ls -lhtr
    - name: Print Something
      run:  cat /etc/*rel* 
  
  second-job:
    needs: [first-job]
    runs-on: ubuntu-latest
    steps:
    - name: Print Something 2
      run:  uname -a
  