name: Testing

on: [push]

jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
    - name: Print Something
      run:  cat /etc/*rel* 
  
  second-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Something 2
      run:  uname -a
  